# .streamlit/secrets.toml (local example - do not commit real secrets)
SPOTIFY_CLIENT_ID = "676d42b45d754be5a11079b0bee1d005"
SPOTIFY_CLIENT_SECRET = "4a92f734fef54acb8fdcf0eb5d9ed296"
DISCOGS_USER_AGENT = "RepositórioRock/1.0 +https://cfmessias.pt"
DISCOGS_TOKEN = "QZUYRfgdNOojzSGPdpKzDttWDKIgAOSXGQGgvzvU"
SPOTIFY_REDIRECT_URI= "http://127.0.0.1:8501"
OMDB_API_KEY = "b6e250d0"

TMDB_API_KEY ="623761d90976c35dc9a34c8932d6a9a2"
TMDB_BEARER  = "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI2MjM3NjFkOTA5NzZjMzVkYzlhMzRjODkzMmQ2YTlhMiIsIm5iZiI6MTc1NjE1OTY1NC4xNzIsInN1YiI6IjY4YWNkZWE2NjFhZmUzMzE4NjFlNTU1MSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.f7x0vRgJ5fJalUqrYJuS2hHXISE2gtg3CCnwtqxRxpg"

# Credenciais lastfm
 self.lastfm_api_key = "9deb9455b2a48404992180122ef70b13"

 # Credenciais discogs
 self.discogs_token = "QZUYRfgdNOojzSGPdpKzDttWDKIgAOSXGQGgvzvU"
 self.discogs_user_agent = "RepositórioRock/1.0 +https://cfmessias.pt"